<!--
**  Agentic Software Engineering (ASE)
**  Copyright (c) 2025-2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
**  Licensed under Apache 2.0 <https://spdx.org/licenses/Apache-2.0>
-->

<template>
    <header>
        <span>
            ⧉ ASE: <span class="val">Task Board</span>
            <span class="sep">·</span>project: <span class="val">{{ board?.project }}</span>
            <span class="sep">·</span>mode: <span class="val">{{ board?.mode }}</span>
            <span class="sep">·</span>tasks: <span class="val">{{ taskCount }}</span>
            <span class="sep">·</span>view: <button class="val toggle" title="switch view (g/l)" @click="setView(view === 'lanes' ? 'graph' : 'lanes')">{{ view }}</button>
            <span class="sep">·</span><span class="filter">filter:
                <span class="field">
                    <input ref="filterEl" v-model="filter" class="val" type="text" autocomplete="off" spellcheck="false"
                        placeholder="keywords…" title="space ANDs, comma ORs fuzzy matched keywords (/)" @keydown.esc="clearFilter" @keydown.enter="filterEl?.blur()">
                    <button v-show="filter !== ''" class="clear" title="clear filter (ESC)" @click="clearFilter">✕</button>
                </span>
            </span>
        </span>
        <span class="warn">{{ warning }}</span>
    </header>
    <div id="view">
        <div v-show="view === 'lanes'" id="board" ref="boardEl" :class="{ titles }" @scroll="updateScroll">
            <template v-if="boardError !== null">{{ boardError }}</template>
            <template v-for="g in board?.groups ?? []" :key="g.title">
                <!--  render each lane of a collapsed group as a narrow box with its
                      vertically written status and number of cards (expanding the group on click)  -->
                <div v-if="surface.collapsed.includes(g.title)" class="group coll">
                    <div class="ghd" @click="toggle('collapsed', g.title)"><span class="arr right">▼</span></div>
                    <div v-for="l in g.lanes" :key="l.status" class="lane"
                        :class="[ { active: l.active, dashed: l.dashed, done: l.kind === 'terminal' }, dropClass(l.status) ]"
                        :style="{ flex: `${l.weight} 1 0` }" @click="toggle('collapsed', g.title)"
                        @dragover="dragOver($event, l.status)" @dragleave="dragLeave($event, l.status)" @drop="drop($event, l.status)">
                        <span class="arr right">▼</span>
                        <span class="vt">{{ l.status.toUpperCase() }}</span>
                        <span class="cnt">{{ l.cards.length }}</span>
                    </div>
                </div>
                <div v-else class="group">
                    <div class="ghd" @click="toggle('collapsed', g.title)"><span class="arr">▼</span> {{ g.title }}</div>
                    <div v-for="l in g.lanes" :key="l.status" class="lane"
                        :class="[ { active: l.active, dashed: l.dashed, done: l.kind === 'terminal', min: surface.minimized.includes(l.status) }, dropClass(l.status) ]"
                        :style="{ flex: `${l.weight} 1 0` }"
                        @dragover="dragOver($event, l.status)" @dragleave="dragLeave($event, l.status)" @drop="drop($event, l.status)">
                        <div class="lhd" @click="toggle('minimized', l.status)">
                            <span>{{ surface.minimized.includes(l.status) ? "▶" : "▼" }} {{ l.status }}</span>
                            <span>{{ l.cards.length }}</span>
                        </div>
                        <div v-if="!surface.minimized.includes(l.status)" class="cards">
                            <div v-for="c in l.cards" :key="c.id" class="card" draggable="true"
                                :class="[ `tone-${c.tone}`, { dragging: drag?.id === c.id } ]" @click="openTask(c.id)"
                                @dragstart="dragStart($event, c.id, l.status, c.moves)" @dragend="dragEnd">
                                <div class="cbody"><span class="cid">{{ c.id }}</span>{{ c.cyclic ? "⟲ " : "" }}{{ c.title }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </template>
        </div>
        <!--  the dependency graph SVG, generated by the service itself (with all texts escaped)  -->
        <!-- eslint-disable-next-line vue/no-v-html -->
        <div v-show="view === 'graph'" id="graph" :class="{ titles }" @click="graphClick" v-html="graph"></div>
    </div>
    <div v-show="view === 'lanes'" id="hscroll">
        <button :style="{ visibility: scroll.all ? 'hidden' : 'visible' }" @click="scrollBy(-240)">◀</button>
        <span>{{ scroll.info }}</span>
        <button :style="{ visibility: scroll.all ? 'hidden' : 'visible' }" @click="scrollBy(240)">▶</button>
    </div>
    <footer>
        <template v-for="(hint, i) in hints" :key="hint.key">
            <template v-if="i > 0"> · </template><kbd>{{ hint.key }}</kbd> {{ hint.action }}
        </template>
    </footer>
    <div v-show="task !== null" id="scrim" @click.self="closeTask">
        <div v-if="task !== null" id="dlg">
            <!--  the header: task id and title on the left, lane group and lane on the right  -->
            <div class="dhd">
                <h1 :class="`tone-${task.tone}`"><span class="cid">{{ task.id }}</span>{{ task.title }}</h1>
                <span class="where"><span class="val">{{ task.group }}</span> ▷ <span class="val">{{ task.status }}</span></span>
                <button class="close" title="close (ESC)" @click="closeTask">✕</button>
            </div>

            <!--  the dependencies: predecessors on the left, successors on the right  -->
            <div class="drefs">
                <span>
                    <span class="mute">predecessors:</span>
                    <span v-if="task.pred.length === 0" class="mute">—</span>
                    <span v-for="r in task.pred" :key="r.id" class="ref" :class="`tone-${r.tone}`" @click="openTask(r.id)">{{ r.id }}</span>
                </span>
                <span>
                    <span class="mute">successors:</span>
                    <span v-if="task.succ.length === 0" class="mute">—</span>
                    <span v-for="r in task.succ" :key="r.id" class="ref" :class="`tone-${r.tone}`" @click="openTask(r.id)">{{ r.id }}</span>
                </span>
            </div>

            <!--  the tabs: the task plan, followed by its attachments, with a
                  scroll arrow on each side where further tabs are hidden  -->
            <div class="dtabs">
                <button class="tarr" :style="{ visibility: tabScroll.less ? 'visible' : 'hidden' }" @click="selectTab(tab - 1)">◁</button>
                <div ref="tabsEl" class="tlist" @scroll="updateTabScroll">
                    <button v-for="(label, i) in task.tabs" :key="i" class="tab" :class="{ sel: i === tab }" @click="selectTab(i)">{{ label }}</button>
                </div>
                <button class="tarr" :style="{ visibility: tabScroll.more ? 'visible' : 'hidden' }" @click="selectTab(tab + 1)">▷</button>
            </div>

            <!--  the content: the rendered task plan or attachment of the selected tab  -->
            <iframe id="plan" ref="planEl" title="task plan"
                sandbox="allow-same-origin allow-popups allow-popups-to-escape-sandbox"
                :srcdoc="tab === 0 ? task.doc : (tabDocs[tab] ?? '')" @load="restorePlanScroll"></iframe>

            <!--  the footer: the key hints  -->
            <div class="dfoot"><kbd>←</kbd>/<kbd>→</kbd> switches tab · <kbd>ESC</kbd> closes</div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, nextTick, watch, onMounted, onBeforeUnmount } from "vue"
import Mousetrap                                                                   from "mousetrap"

/*  the board model and task details, as delivered by the service  */
type Card    = { id: string, title: string, cyclic: boolean, tone: string, moves?: string[] }
type Lane    = { status: string, active: boolean, weight: number, dashed: boolean, kind: "initial" | "regular" | "terminal", cards: Card[] }
type Group   = { title: string, lanes: Lane[] }
type Surface = { minimized: string[], collapsed: string[], titles: boolean }
type Board   = { mode: string, project: string, warnings: string[], surface: Surface, moves: Record<string, string[]>, groups: Group[] }
type Tone    = "active" | "done" | "idle"
type Ref     = { id: string, tone: Tone }
type Task    = { id: string, title: string, tone: Tone, status: string, group: string, doc: string, tabs: string[], pred: Ref[], succ: Ref[] }
type View    = "lanes" | "graph"

/*  fetch a JSON response of the service  */
type Result<T> = (T & { error?: undefined }) | { error: string }
const api = async <T>(url: string, opts?: RequestInit): Promise<Result<T>> => {
    try {
        return await (await fetch(url, opts)).json()
    }
    catch (err: unknown) {
        return { error: err instanceof Error ? err.message : String(err) }
    }
}

/*  the state of the page  */
const board       = ref<Board | null>(null)
const boardError  = ref<string | null>(null)
const actionError = ref<string | null>(null)
const view        = ref<View>("lanes")
const graph       = ref("")
const task        = ref<Task | null>(null)
const boardEl     = ref<HTMLElement | null>(null)
const planEl      = ref<HTMLIFrameElement | null>(null)
const tabsEl      = ref<HTMLElement | null>(null)
const scroll      = reactive({ all: true, info: "" })
const tab         = ref(0)
const tabDocs     = ref<Record<number, string>>({})
const tabScroll   = reactive({ less: false, more: false })
const tabScrolls  = new Map<number, number>()
const filter      = ref("")
const filterEl    = ref<HTMLInputElement | null>(null)
let   query       = ""
let   openId      = null as string | null
let   openSeq     = 0
let   reloadSeq   = 0
let   graphSeq    = 0

/*  the derived values of the page  */
const surface   = computed<Surface>(() => board.value?.surface ?? { minimized: [], collapsed: [], titles: false })
const titles    = computed(() => surface.value.titles)
const taskCount = computed(() => {
    const cards = board.value?.groups.flatMap((g) => g.lanes).flatMap((l) => l.cards)
    return cards === undefined ? "" : `${cards.filter((c) => c.tone !== "done").length}/${cards.length}`
})

const warning   = computed(() => actionError.value !== null ? `⚠ ${actionError.value}` :
    (board.value?.warnings.length ?? 0) > 0 ? `⚠ ${board.value!.warnings.join(" · ")}` : "")
const hints     = computed(() => [
    { key: "Left-Click", action: view.value === "lanes" ? "view task / minimize/maximize lane / collapse/expand group" : "view task" },
    ...(view.value === "lanes" ? [ { key: "Drag & Drop", action: "move task to lane" } ] : []),
    { key: "/",          action: "filter tasks" },
    { key: "t",          action: `${titles.value ? "collapse" : "expand"} titles` },
    view.value === "lanes" ? { key: "g", action: "switch to graph" } : { key: "l", action: "switch to lanes" },
    { key: "ESC",        action: "close task" }
])

/*  determine the visible groups of the horizontally scrollable lanes view  */
const updateScroll = () => {
    const el = boardEl.value
    if (el === null)
        return
    const groups  = [ ...el.querySelectorAll<HTMLElement>(".group") ]
    const visible = groups.map((g, i) => ({ g, i })).filter(({ g }) =>
        g.offsetLeft + g.offsetWidth > el.scrollLeft + 1 && g.offsetLeft < el.scrollLeft + el.clientWidth - 1)
    scroll.all  = visible.length === groups.length
    scroll.info = visible.length === 0 ? "" : `groups ${visible[0].i + 1}–${visible[visible.length - 1].i + 1} ` +
        `of ${groups.length}${scroll.all ? " · all visible" : " · scroll or ◀/▶"}`
}
const scrollBy = (left: number) =>
    boardEl.value?.scrollBy({ left, behavior: "smooth" })
watch([ board, view ], () => nextTick(updateScroll), { deep: true })

/*  load the dependency graph (laid out by the service)  */
const renderGraph = async () => {
    const seq = ++graphSeq
    const res = await api<{ svg: string }>(`/task-board/api/graph?filter=${encodeURIComponent(query)}`)
    if (seq !== graphSeq)
        return
    graph.value = res.error !== undefined ? `<p class="warn">${res.error.replace(/[&<>]/g, (c) => `&#${c.charCodeAt(0)};`)}</p>` :
        res.svg !== "" ? res.svg : "<p class=\"mute\">(no tasks)</p>"
}
const graphClick = (ev: MouseEvent) => {
    const node = (ev.target as Element).closest<SVGGElement>("g.node[data-id]")
    if (node !== null)
        openTask(node.dataset.id!)
}

/*  remember the scroll position of the document of the selected tab  */
const keepTabScroll = () => {
    const win = planEl.value?.contentWindow ?? null
    if (task.value !== null && win !== null)
        tabScrolls.set(tab.value, win.scrollY)
}

/*  open the dialog of a task, keeping the selected tab and the scroll
    positions of the tab documents when re-opening the same task (on changes)  */
const openTask = async (id: string) => {
    const seq = ++openSeq
    if (openId === id)
        keepTabScroll()
    else {
        tab.value = 0
        tabScrolls.clear()
    }
    openId = id
    const t = await api<Task>(`/task-board/api/task/${encodeURIComponent(id)}`)
    if (seq !== openSeq)
        return
    if (t.error !== undefined) {
        closeTask()
        return
    }

    /*  replace the cached attachment documents only once the selected one is re-fetched  */
    const n   = Math.min(tab.value, t.tabs.length - 1)
    const doc = n > 0 ? await fetchTabDoc(id, n) : ""
    if (seq !== openSeq)
        return
    tabDocs.value = n > 0 ? { [n]: doc } : {}
    task.value    = t
    tab.value     = n
    nextTick(updateTabScroll)
}
const restorePlanScroll = () => {
    planEl.value?.contentWindow?.scrollTo(0, tabScrolls.get(tab.value) ?? 0)
}
const closeTask = () => {
    openSeq++
    openId     = null
    task.value = null
}

/*  fetch the document of an attachment tab, or load it into the cache
    (the task plan tab has its document already)  */
const fetchTabDoc = async (id: string, n: number): Promise<string> => {
    const d = await api<{ doc: string }>(`/task-board/api/task/${encodeURIComponent(id)}/attachment/${n - 1}/doc`)
    return d.error !== undefined ? `<p class="warn">${d.error.replace(/[&<>]/g, (c) => `&#${c.charCodeAt(0)};`)}</p>` : d.doc
}
const loadTab = async (n: number) => {
    if (n === 0 || task.value === null || tabDocs.value[n] !== undefined)
        return
    const id  = task.value.id
    const doc = await fetchTabDoc(id, n)
    if (task.value?.id === id)
        tabDocs.value[n] = doc
}

/*  select a tab of the task dialog, scrolled into the visible part of the tab bar  */
const selectTab = async (n: number) => {
    if (task.value === null || n < 0 || n >= task.value.tabs.length || n === tab.value)
        return
    keepTabScroll()
    tab.value = n
    nextTick(() => tabsEl.value?.children[n]?.scrollIntoView({ block: "nearest", inline: "nearest" }))
    await loadTab(n)
}

/*  determine whether further tabs are hidden on the left or right side of the tab bar  */
const updateTabScroll = () => {
    const el = tabsEl.value
    if (el === null)
        return
    tabScroll.less = el.scrollLeft > 1
    tabScroll.more = el.scrollLeft + el.clientWidth < el.scrollWidth - 1
}

/*  (re)load the board model  */
const reload = async () => {
    const seq  = ++reloadSeq
    const data = await api<Board>(`/task-board/api/board?filter=${encodeURIComponent(query)}`)
    if (seq !== reloadSeq)
        return
    if (data.error !== undefined) {
        boardError.value = data.error
        return
    }
    boardError.value = null
    board.value = data
    if (view.value === "graph")
        await renderGraph()
    if (openId !== null)
        await openTask(openId)
}

/*  apply the filter query debounced while typing (as each change
    re-fetches the board), or immediately when it is cleared  */
let filterTimer: ReturnType<typeof setTimeout> | null = null
watch(filter, (value) => {
    if (filterTimer !== null)
        clearTimeout(filterTimer)
    filterTimer = setTimeout(() => {
        filterTimer = null
        query = value
        reload()
    }, value === "" ? 0 : 250)
})
const clearFilter = () => {
    filter.value = ""
    filterEl.value?.blur()
}

/*  apply a changed surface state, with the graph re-laid out if the showing of titles changed  */
const applySurface = (s: Surface) => {
    if (board.value === null)
        return
    const relayout = board.value.surface.titles !== s.titles
    board.value.surface = s
    if (relayout && view.value === "graph")
        renderGraph()
}

/*  drag & drop a task box onto another lane, changing the task status: only
    lanes whose state is reachable in the lifecycle model accept the drop
    (from the actual status of the task, if it is foreign to the model)  */
const drag = ref<{ id: string, from: string, moves?: string[], over: string | null } | null>(null)
const canDrop = (status: string) =>
    drag.value !== null && (drag.value.moves ?? board.value?.moves[drag.value.from] ?? []).includes(status)
const dropClass = (status: string) => drag.value === null ? {} : {
    target:  canDrop(status),
    over:    canDrop(status) && drag.value.over === status,
    blocked: !canDrop(status) && status !== drag.value.from
}
const dragStart = (ev: DragEvent, id: string, from: string, moves?: string[]) => {
    drag.value = { id, from, moves, over: null }
    if (ev.dataTransfer !== null) {
        ev.dataTransfer.setData("text/plain", id)
        ev.dataTransfer.effectAllowed = "move"
    }
}
const dragOver = (ev: DragEvent, status: string) => {
    if (!canDrop(status))
        return
    ev.preventDefault()
    if (ev.dataTransfer !== null)
        ev.dataTransfer.dropEffect = "move"
    drag.value!.over = status
}
const dragLeave = (ev: DragEvent, status: string) => {
    if (drag.value?.over === status && !(ev.currentTarget as Element).contains(ev.relatedTarget as Node | null))
        drag.value.over = null
}
const dragEnd = () => {
    drag.value = null
}
const drop = async (ev: DragEvent, status: string) => {
    ev.preventDefault()
    const d = drag.value
    if (d === null || !canDrop(status))
        return
    drag.value = null
    const res = await api<{ from: string, to: string }>("/task-board/api/move", {
        method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: d.id, status })
    })
    actionError.value = res.error ?? null
}

/*  toggle a minimized lane, a collapsed group, or the showing of task titles  */
const toggle = async (list: "minimized" | "collapsed" | "titles", entry: string) => {
    const s = await api<Surface>("/task-board/api/toggle", {
        method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ list, entry })
    })
    if (s.error !== undefined) {
        actionError.value = s.error
        return
    }
    actionError.value = null
    applySurface(s)
}

/*  switch between the lanes and the graph view  */
const setView = (v: View) => {
    view.value = v
    if (v === "graph")
        renderGraph()
}

/*  connect to the service: change events, keyboard shortcuts, and keep-alive  */
let events: EventSource | null = null
let ping: ReturnType<typeof setInterval> | null = null
const onKey = (ev: KeyboardEvent) => {
    if (ev.key === "Escape")
        closeTask()
    else if (task.value !== null && (ev.key === "ArrowLeft" || ev.key === "ArrowRight")) {
        ev.preventDefault()
        selectTab(tab.value + (ev.key === "ArrowLeft" ? -1 : 1))
    }
}
const onResize = () => {
    updateScroll()
    updateTabScroll()
}
onMounted(() => {
    events = new EventSource("/task-board/events")
    events.addEventListener("change", () => reload())
    events.addEventListener("open", () => { if (board.value !== null) reload() })
    events.addEventListener("surface", (ev) => applySurface(JSON.parse((ev as MessageEvent).data)))
    Mousetrap.bind("t", () => { if (board.value !== null) toggle("titles", "") })
    Mousetrap.bind("g", () => { if (view.value !== "graph") setView("graph") })
    Mousetrap.bind("l", () => { if (view.value !== "lanes") setView("lanes") })
    Mousetrap.bind("/", (ev) => {
        ev.preventDefault()
        filterEl.value?.focus()
    })
    document.addEventListener("keydown", onKey)
    window.addEventListener("resize", onResize)
    ping = setInterval(() => api("/task-board/api/ping"), 60 * 1000)
    reload()
})
onBeforeUnmount(() => {
    events?.close()
    Mousetrap.reset()
    document.removeEventListener("keydown", onKey)
    window.removeEventListener("resize", onResize)
    if (ping !== null)
        clearInterval(ping)
    if (filterTimer !== null)
        clearTimeout(filterTimer)
})
</script>

<style lang="stylus" src="./ase-task-board-web-client.styl"></style>

