##
##  Agentic Software Engineering (ASE)
##  Copyright (c) 2025-2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under GPL 3.0 <https://spdx.org/licenses/GPL-3.0-only>
##

#   build project
build
    (cd tool && npm start build)

#   publish new release of project
publish : build
    node etc/version.mts && \
    version="$(qq -r .version package.json)"
    git commit \
        -a -m "update version to $version" \
        package.json \
        tool/package.json \
        plugin/.claude-plugin/plugin.json && \
    git tag "$version" && \
    git push && \
    git push --tags && \
    (cd tool && npm publish)

#   remove regularly built files
clean
    shx rm -rf dst

#   remove all built files
distclean: clean
    shx rm -f package-lock.json
    shx rm -rf node_modules

