#!/usr/bin/env node

/*  built-in dependencies  */
const path          = require("node:path")
const fs            = require("node:fs")
const child_process = require("node:child_process")

/*  determine path to external files  */
const file_pkg = path.join(process.env.CLAUDE_PLUGIN_ROOT, ".claude-plugin/plugin.json")
const file_md  = path.join(process.env.CLAUDE_PLUGIN_ROOT, "meta/ase-constitution.md")

/*  read external files  */
const pkg = fs.readFileSync(file_pkg, "utf8")
let   md  = fs.readFileSync(file_md,  "utf8")

/*  determine own version  */
const version = JSON.parse(pkg).version ?? ""

/*  read session information  */
const stdin = fs.readFileSync(0, "utf8")
const input = stdin.trim() !== "" ? JSON.parse(stdin) : {}

/*  determine session id  */
const sessionId = input.session_id ?? ""

/*  determine task id  */
let taskId = process.env.ASE_TASK_ID ?? "default"
try {
    child_process.execSync(
        `ase config --scope="session:${sessionId}" set task.id "${taskId}"`,
        { stdio: [ "ignore", "ignore", "ignore" ] }).toString().trim()
}
catch (_e) {
}

/*  provide session and task id to shell commands  */
const envFile = process.env.CLAUDE_ENV_FILE ?? ""
if (envFile !== "") {
    const script =
        `export ASE_VERSION="${version}"\n` +
        `export ASE_SESSION_ID="${sessionId}"\n` +
        `export ASE_TASK_ID="${taskId}"\n`
    fs.appendFileSync(envFile, script, "utf8")
}

/*  prepend ASE information to constitution markdown  */
md =
    `<ase-version>${version}</ase-version>\n` +
    `<ase-task-id>${taskId}</ase-task-id>\n` +
    `<ase-session-id>${sessionId}</ase-session-id>\n` +
    "\n" + md

/*  inject information into session context  */
process.stdout.write(JSON.stringify({
    "hookSpecificOutput": {
        "hookEventName": "SessionStart",
        "additionalContext": md
    }
}))

